### ISSUE TITLE
Missing lodash lib in prod

### ISSUE THREAD

**Issue by jonyrock** [CorpGlory/grafana-data-exporter#20]
from production. https://github.com/CorpGlory/grafana-data-exporter/wiki/Getting-Started-Linux , `grafana-data-exporter-0.3.3`

I run `$ node dist/server.js` and get error: 

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.P (/home/alex/grafana-data-exporter-0.3.3/dist/server.js:784:18)
    at __webpack_require__ (/home/alex/grafana-data-exporter-0.3.3/dist/server.js:638:30)
    at fn (/home/alex/grafana-data-exporter-0.3.3/dist/server.js:48:20)
    at Object.<anonymous> (/home/alex/grafana-data-exporter-0.3.3/dist/server.js:696:11)
    at __webpack_require__ (/home/alex/grafana-data-exporter-0.3.3/dist/server.js:638:30)
    at fn (/home/alex/grafana-data-exporter-0.3.3/dist/server.js:48:20)
```

**Comment by jonyrock** [comment]
@rozetko  @amper43 
such config works good for development, not production. 
https://github.com/CorpGlory/grafana-data-exporter/blob/master/build/webpack.base.conf.js#L24
```
externals: [
    function(context, request, callback) {
      if(request[0] == '.') {
        callback();
      } else {
        callback(null, "require('" + request + "')");
      }
    }
  ],
```

but you keep in in `base` config
