### ISSUE TITLE
Receiving "Cannot read property 'queries' of undefined" while using PostgreSQL dashboard

### ISSUE THREAD

**Issue by Karan96Kaushik** [CorpGlory/grafana-data-exporter#23]
(node:9864) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'queries' of undefined
    at PostgresMetric.getQuery (/home/karansgs/Documents/GRAFANA/grafana-data-exporter-0.3.6/dist/server.js:45898:44)
    at Object.<anonymous> (/home/karansgs/Documents/GRAFANA/grafana-data-exporter-0.3.6/dist/server.js:28160:44)
    at Generator.next (<anonymous>)
    at /home/karansgs/Documents/GRAFANA/grafana-data-exporter-0.3.6/dist/server.js:28113:71
    at new Promise (<anonymous>)
    at __awaiter (/home/karansgs/Documents/GRAFANA/grafana-data-exporter-0.3.6/dist/server.js:28109:12)
    at Object.queryByMetric (/home/karansgs/Documents/GRAFANA/grafana-data-exporter-0.3.6/dist/server.js:28147:12)
    at Target.<anonymous> (/home/karansgs/Documents/GRAFANA/grafana-data-exporter-0.3.6/dist/server.js:45543:62)
    at Generator.next (<anonymous>)
    at /home/karansgs/Documents/GRAFANA/grafana-data-exporter-0.3.6/dist/server.js:45482:71
(node:9864) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)

**Comment by jonyrock** [comment]
@Karan96Kaushik can I ask you to show the query you are running in grafana? 
(datasource tab)

**Comment by rozetko** [comment]
fixed in [0.4.0 version](https://github.com/CorpGlory/grafana-data-exporter/releases/tag/0.4.0)
